### PR TITLE
Add support for loading compiled code, bug fixes for R15B

### PR DESCRIPTION
**Pull request by ericbmerritt**

### CODE REVIEW

**Comment by jwilberding** [comment]
Smoketests fail:

# 

## FAIL: test_xref (**main**.TestXref)

Traceback (most recent call last):
  File "/home/diginux/code/sinan/smoketests/tests/xref_test.py", line 22, in test_xref
    self.do_run(app_desc)
  File "/home/diginux/code/sinan/smoketests/sin_testing/**init**.py", line 285, in do_run
    "do_dist"], a)
  File "/home/diginux/code/sinan/smoketests/sin_testing/**init**.py", line 133, in do_apply
    res = f(res)
  File "/home/diginux/code/sinan/smoketests/sin_testing/**init**.py", line 61, in new_f
    res = f(self, child, _(args[1:]), *_kwds)
  File "/home/diginux/code/sinan/smoketests/sin_testing/**init**.py", line 254, in do_release
    "sys.config")
  File "/home/diginux/code/sinan/smoketests/sin_testing/**init**.py", line 127, in assert_files_exist
    self.assertTrue(os.path.isfile(check_file))
AssertionError

---

Ran 1 test in 10.478s

FAILED (failures=1)
make: **\* [smoketests] Error 1

**Comment by ericbmerritt** [comment]
Any idea why they are failing? They all passed for me.

**Comment by jwilberding** [comment]
I seem to have several of these:

build problem error:{badarg,[no_warn_sasl]}:[{systools_make,make_script,
                                              ["smprj",
                                               [no_warn_sasl,
                                                {outdir,
                                                 "/tmp/smoke_test_UYKeE9/smprj/_build/smprj/releases/0.21.0.0"},
                                                {path,
                                                 ["/tmp/smoke_test_UYKeE9/smprj/_build/smprj/releases/0.21.0.0",
                                                  "/usr/local/lib/erlang/lib/kernel-2.14.5/ebin",
                                                  "/usr/local/lib/erlang/lib/stdlib-1.17.5/ebin",
                                                  "/tmp/smoke_test_UYKeE9/smprj/_build/smprj/lib/app2-0.1.0/ebin",
                                                  "/tmp/smoke_test_UYKeE9/smprj/_build/smprj/lib/app3-0.1.0/ebin",
                                                  "/tmp/smoke_test_UYKeE9/smprj/_build/smprj/lib/app1-0.1.0/ebin"]},
                                                no_module_tests,silent]]},
                                             {sin_task_release,
                                              make_boot_script,2},
                                             {sin_task_release,do_task,2},
                                             {sinan,'-run_task/4-fun-1-',4},
                                             {lists,foldl,3},
                                             {sinan,do_task_full,3},
                                             {sinan,do_task,3},
                                             {sinan,do,3}]
Checking version directory at /tmp/smoke_test_UYKeE9/smprj/_build/smprj/releases/0.21.0.0

# F

## FAIL: test_hooks (**main**.TestHooks)

Traceback (most recent call last):
  File "/home/diginux/code/sinan/smoketests/tests/hooks_test.py", line 52, in test_hooks
    self.do_run(app_desc)
  File "/home/diginux/code/sinan/smoketests/tests/hooks_test.py", line 41, in do_run
    "do_dist"], na)
  File "/home/diginux/code/sinan/smoketests/sin_testing/**init**.py", line 133, in do_apply
    res = f(res)
  File "/home/diginux/code/sinan/smoketests/sin_testing/**init**.py", line 61, in new_f
    res = f(self, child, _(args[1:]), *_kwds)
  File "/home/diginux/code/sinan/smoketests/sin_testing/**init**.py", line 254, in do_release
    "sys.config")
  File "/home/diginux/code/sinan/smoketests/sin_testing/**init**.py", line 127, in assert_files_exist
    self.assertTrue(os.path.isfile(check_file))
AssertionError

**Comment by ericbmerritt** [comment]
ok. It looks like the problem is on the no_warn_sasl option that was introduced in R15B. Apperantly, Ericsson wanted a warning that almost no one else uses and made it a default. I didn't realize that I could only pass it in R15B. I will set it up so that I introspect the erlang version and only pass that in R15B or greater. _sigh_ The should _not_ have made it a default option really. Suddenly things are not backwards compatible at the release building level. I will update this pull request.

**Comment by ericbmerritt** [comment]
Closing this out to get around a problem in github

**Pull request closed without merging**
